openapi: 3.0.0
info:
  title: first-bot-apigw
  version: 1.0.0
paths:
  /forwebhook:
    post:
      x-yc-apigateway-integration:
        type: cloud-functions
        function_id: d4euut33ru6en33veb3d
        service_account_id: aje30otop4j0tmok8mkp
      operationId: first-bot-function
